language: go

go_import_path: github.com/braumye/grobot

go:
  - 1.11.x
  - 1.12.x

script:
  - go vet
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
